// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { Button, HorizontalBox, VerticalBox } from "std-widgets.slint";
import { Page } from "page.slint";

export component About inherits Page {
    title: @tr("About");

    VerticalBox {
        alignment: start;
        HorizontalBox {
            alignment: center;
            Button {
                text: @tr("Wiki");
            }
        }

        HorizontalBox {
            alignment: center;
            Button {
                text: @tr("Discord Server");
            }
        }

        HorizontalBox {
            alignment: center;
            Text {
                text: @tr("Version: 0.1.0");
            }
        }

        property <bool> has_update: true;
        if has_update:HorizontalBox {
            alignment: center;
            Button {
                text: @tr("Download new version");
            }
        }
    }
}
