import { HorizontalBox, VerticalBox, Button, LineEdit, Switch, Slider } from "std-widgets.slint";
import { Page } from "page.slint";

export global InputProfileData {
    in-out property <bool> dinput;
    in-out property <string> profile_name;
    in-out property <int> deadzone;
    in-out property <bool> show_input_profile;
    in-out property <bool> capturing;
    in-out property <string> capture_label;
    in-out property <int> capture_index;
    in-out property <int> capture_total: 19;
}

export component InputProfileDialog inherits Page {
    title: @tr("Create/Modify Input Profile");
    callback profile_creation_button_clicked;
    in-out property dinput <=> InputProfileData.dinput;
    in-out property profile_name <=> InputProfileData.profile_name;
    in-out property deadzone <=> InputProfileData.deadzone;
    VerticalBox {
        alignment: start;

        HorizontalBox {
            alignment: center;
            vertical-stretch: 0;
            LineEdit {
                vertical-stretch: 0;
                placeholder-text: @tr("Enter profile name to create or modify");
                text: InputProfileData.profile_name;
                preferred-width: 400px;
                edited(text) => {
                    InputProfileData.profile_name = text;
                }
            }
        }

        HorizontalBox {
            vertical-stretch: 0;
            alignment: center;
            Text {
                text: @tr("Deadzone Percentage");
                vertical-alignment: center;
            }

            Slider {
                min-width: 160px;
                maximum: 99;
                value: InputProfileData.deadzone;
                changed(value) => {
                    InputProfileData.deadzone = value;
                }
            }

            Text {
                text: InputProfileData.deadzone + "%";
                vertical-alignment: center;
            }
        }

        HorizontalBox {
            vertical-stretch: 0;
            alignment: center;
            Switch {
                text: @tr("Use DirectInput");
                checked: InputProfileData.dinput;
                toggled => {
                    InputProfileData.dinput = self.checked;
                }
            }
        }

        HorizontalBox {
            alignment: center;
            vertical-stretch: 0;
            Button {
                vertical-stretch: 0;
                text: @tr("Start Profile Creation Wizard");
                enabled: InputProfileData.profile_name != "" && InputProfileData.profile_name != "default";
                clicked => {
                    profile_creation_button_clicked();
                }
            }
            Button {
                vertical-stretch: 0;
                text: @tr("Cancel");
                clicked => {
                    InputProfileData.show_input_profile = false;
                }
            }
        }
    }
}
