import { VerticalBox, HorizontalBox, TextEdit, ScrollView, LineEdit, Button, GridBox } from "std-widgets.slint";
import { NetplayData } from "netplay_page.slint";

export global NetplayWaitData {
    in-out property <string> chat_message;
    in-out property <string> motd;
    in-out property <[string]> players;
    in-out property <int> port;
}

export component NetplayWait inherits Window {
    title: @tr("Netplay: Waiting Room");
    preferred-width: 400px;
    preferred-height: 400px;
    in-out property players <=> NetplayWaitData.players;
    in-out property session_name <=> NetplayData.session_name;
    in-out property game_name <=> NetplayData.game_name;
    in-out property motd <=> NetplayWaitData.motd;
    in-out property port <=> NetplayWaitData.port;
    VerticalBox {
        Text {
            text: @tr("Session Name: ") + NetplayData.session_name;
            font-size: 15px;
            horizontal-alignment: center;
        }

        Text {
            text: @tr("Game Name: ") + NetplayData.game_name;
            font-size: 15px;
            horizontal-alignment: center;
        }

        GridBox {
            Row {
                Text {
                    text: "Player 1: " + players[0];
                }

                Text {
                    text: "Player 2: " + players[1];
                }
            }

            Row {
                Text {
                    text: "Player 3: " + players[2];
                }

                Text {
                    text: "Player 4: " + players[3];
                }
            }
        }

        TextEdit {
            read-only: true;
            text: @tr("Chat data");
        }

        HorizontalBox {
            LineEdit {
                placeholder_text: @tr("Enter chat message");
                edited(text) => {
                    NetplayWaitData.chat_message = text;
                }
            }

            Button {
                text: @tr("Send Message");
                enabled: NetplayWaitData.chat_message != "";
            }
        }

        Text {
            text: NetplayWaitData.motd;
            wrap: word-wrap;
        }

        Button {
            text: @tr("Start Game");
        }
    }
}
