import { VerticalBox, LineEdit, StandardTableView, HorizontalBox, ComboBox, Button } from "std-widgets.slint";
import { NetplayData } from "netplay_page.slint";

export global NetplayJoinData {
    in-out property <string> player_name;
}

export component NetplayJoin inherits Window {
    title: @tr("Netplay: Join Session");
    property <bool> has_sessions: false;
    in-out property server_names <=> NetplayData.server_names;

    VerticalBox {
        HorizontalBox {
            VerticalBox {
                Text {
                    text: @tr("Player Name:");
                }

                LineEdit {
                    placeholder_text: @tr("Enter player name");
                    edited(text) => {
                        NetplayJoinData.player_name = text;
                    }
                }
            }

            VerticalBox {
                Text {
                    text: @tr("Server:");
                }

                HorizontalBox {
                    ComboBox {
                        model: NetplayData.server_names;
                    }

                    Text {
                        vertical-alignment: center;
                        text: @tr("Ping: 100ms");
                    }
                }
            }
        }

        if has_sessions:StandardTableView {
            columns: [
                { title: "Header 1" },
                { title: "Header 2" },
            ];
            rows: [
                [
                    { text: "Item 1" },
                    { text: "Item 2" },
                ],
                [
                    { text: "Item 1" },
                    { text: "Item 2" },
                ],
                [
                    { text: "Item 1" },
                    { text: "Item 2" },
                ]
            ];
        }
        if !has_sessions: Text {
            text: @tr("No sessions available. Please refresh or try a different server.");
            horizontal-alignment: center;
            vertical-alignment: center;
        }

        HorizontalBox {
            Rectangle { }

            Button {
                text: @tr("Refresh Session List");
            }
        }

        HorizontalBox {
            LineEdit {
                placeholder-text: @tr("Password (if required)");
            }

            Button {
                text: @tr("Join Session (Open ROM)");
                enabled: NetplayJoinData.player_name != "";
            }
        }
    }
}
