import { Palette, StandardButton, LineEdit, HorizontalBox, VerticalBox, Button, ComboBox, ScrollView } from "std-widgets.slint";
import { NetplayData } from "netplay_page.slint";
import { SettingsData } from "settings_page.slint";
import { Page } from "page.slint";

export component NetplayCreate inherits Page {
    title: @tr("Netplay: Create Session");
    callback get_custom_url();
    callback select_rom(string);
    callback create_session(string, string, string, string, string, string, string);
    callback close;

    VerticalBox {
        alignment: start;
        HorizontalBox {
            alignment: center;
            VerticalBox {
                alignment: start;
                horizontal-stretch: 0;
                HorizontalBox {
                    VerticalBox {
                        Text {
                            text: @tr("Session Name:");
                        }

                        LineEdit {
                            placeholder-text: @tr("Enter session name");
                            text: NetplayData.session_name;
                            edited(text) => {
                                NetplayData.session_name = text;
                            }
                        }
                    }

                    VerticalBox {
                        Text {
                            text: @tr("Password (Optional):");
                        }

                        LineEdit {
                            placeholder-text: @tr("Enter session password");
                            text: NetplayData.password;
                            edited(text) => {
                                NetplayData.password = text;
                            }
                        }
                    }
                }

                VerticalBox {
                    Text {
                        text: @tr("Player Name:");
                    }

                    LineEdit {
                        placeholder-text: @tr("Enter player name");
                        text: NetplayData.player_name;
                        edited(text) => {
                            NetplayData.player_name = text;
                        }
                    }
                }

                VerticalBox {
                    Text {
                        text: @tr("Server:");
                    }

                    HorizontalBox {
                        server := ComboBox {
                            model: NetplayData.server_names;
                            selected => {
                                if (self.current-index >= 0) {
                                    if (self.current-value == "Custom") {
                                        get_custom_url();
                                    }
                                }
                            }
                        }
                    }
                }

                HorizontalBox {
                    alignment: center;
                    if NetplayData.game_name == "": Button {
                        text: @tr("Select ROM");
                        clicked => {
                            select_rom(SettingsData.rom_dir);
                        }
                    }
                    if NetplayData.game_name != "": Button {
                        text: NetplayData.game_name;
                        clicked => {
                            select_rom(SettingsData.rom_dir);
                        }
                    }
                }

                Rectangle { }

                if NetplayData.game_cheats != "": Text {
                    text: @tr("This game has cheats enabled. Cheats will be synchronized with other players.");
                    horizontal-alignment: center;
                    wrap: word-wrap;
                }
                Rectangle { }

                HorizontalBox {
                    alignment: center;
                    Button {
                        property <string> server_url;
                        text: @tr("Create Session");
                        enabled: NetplayData.session_name != "" && NetplayData.player_name != "" && NetplayData.game_name != "" && !NetplayData.pending_session;
                        clicked => {
                            NetplayData.pending_session = true;
                            if (server.current-value == "Custom") {
                                server_url = "ws://" + NetplayData.custom_server_url;
                            } else {
                                server_url = NetplayData.server_urls[server.current-index];
                            }
                            create_session(
                            server_url,
                            NetplayData.session_name,
                            NetplayData.player_name,
                            NetplayData.game_name,
                            NetplayData.game_hash,
                            NetplayData.game_cheats,
                            NetplayData.password);
                        }
                    }
                    Button {
                        text: @tr("Cancel");
                        clicked => {
                            close();
                        }
                    }
                }
                Rectangle { }
            }
        }
    }
}

export component CustomServerDialog inherits PopupWindow {
    close-policy: no-auto-close;
    Rectangle {
        height:100%;
        width: 100%;
        background: Palette.background;
        VerticalBox {
            alignment: center;
            HorizontalBox{
                alignment: center;
                Text {
                    text: @tr("Enter a custom server URL");
                }
            }
            HorizontalBox {
                alignment: center;
                vertical-stretch: 0;
                LineEdit {
                    vertical-stretch: 0;
                    text: NetplayData.custom_server_url;
                    placeholder-text: "example.com:45000";
                    preferred-width: 300px;
                    edited(text) => {
                        NetplayData.custom_server_url = text;
                    }
                }
            }
            HorizontalBox{
                alignment: center;
                StandardButton {
                    kind: ok;
                    clicked() => {
                        root.close();
                    }
                }
            }
        }
    }
}
