// Copyright © SixtyFPS GmbH <info@slint.dev>
// SPDX-License-Identifier: MIT

import { ComboBox, HorizontalBox, VerticalBox, CheckBox } from "std-widgets.slint";
import { Page } from "page.slint";

export component Settings inherits Page {
    in-out property <bool> integer_scaling;
    in-out property <bool> fullscreen;
    in-out property <bool> widescreen;
    in-out property <bool> apply_crt_shader;
    in-out property <bool> overclock_n64_cpu;
    in-out property <string> resolution;
    title: @tr("Settings");

    VerticalBox {
        alignment: start;
        HorizontalBox {
            alignment: start;
            Text {
                text: @tr("Resolution:");
                vertical-alignment: center;
            }

            ComboBox {
                model: ["1x", "2x", "4x"];
                current-value: resolution;
            }
        }

        HorizontalBox {
            alignment: start;
            CheckBox {
                text: @tr("Integer Scaling");
                checked: integer_scaling;
            }
        }

        HorizontalBox {
            alignment: start;
            CheckBox {
                text: @tr("Fullscreen (Esc closes game)");
                checked: fullscreen;
            }
        }

        HorizontalBox {
            alignment: start;
            CheckBox {
                text: @tr("Widescreen (strech)");
                checked: widescreen;
            }
        }

        HorizontalBox {
            alignment: start;
            CheckBox {
                text: @tr("Apply CRT shader");
                checked: apply_crt_shader;
            }
        }

        Rectangle { }

        HorizontalBox {
            alignment: start;
            CheckBox {
                text: @tr("Overclock N64 CPU (may cause bugs)");
                checked: overclock_n64_cpu;
            }
        }
    }
}
